param(
    [string]$TaskName = "AutoSaham-KillSwitchWeeklyDrill",
    [ValidateSet("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday")]
    [string]$DayOfWeek = "Sunday",
    [string]$At = "07:00",
    [string]$BaseUrl = "http://127.0.0.1:8000",
    [string]$Actor = "ops-weekly-drill",
    [string]$ChallengeCode = "",
    [string]$AuthTokenEnvVar = "AUTOSAHAM_KILL_SWITCH_DRILL_AUTH_TOKEN",
    [switch]$Force
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Convert-ToSingleQuotedLiteral {
    param([string]$Value)
    return [string]$Value -replace "'", "''"
}

$scriptPath = Join-Path $PSScriptRoot "kill_switch_drill.ps1"
if (-not (Test-Path $scriptPath)) {
    throw "kill_switch_drill.ps1 not found at: $scriptPath"
}

$escapedScriptPath = Convert-ToSingleQuotedLiteral $scriptPath
$escapedBaseUrl = Convert-ToSingleQuotedLiteral $BaseUrl
$escapedActor = Convert-ToSingleQuotedLiteral $Actor
$escapedAuthVar = Convert-ToSingleQuotedLiteral $AuthTokenEnvVar

$challengeArg = ""
if (-not [string]::IsNullOrWhiteSpace($ChallengeCode)) {
    $escapedChallenge = Convert-ToSingleQuotedLiteral $ChallengeCode
    $challengeArg = " -ChallengeCode '$escapedChallenge'"
}

# Resolve auth token at execution time from environment variable on the host.
$psCommand = "& '$escapedScriptPath' -BaseUrl '$escapedBaseUrl' -Actor '$escapedActor' -AuthToken ([Environment]::GetEnvironmentVariable('$escapedAuthVar'))$challengeArg"
$actionArgs = "-NoProfile -ExecutionPolicy Bypass -Command `"$psCommand`""
$action = New-ScheduledTaskAction -Execute "powershell.exe" -Argument $actionArgs
$trigger = New-ScheduledTaskTrigger -Weekly -DaysOfWeek $DayOfWeek -At $At

$description = "AutoSaham weekly kill-switch rehearsal drill (generated by register_kill_switch_drill_task.ps1)"

if ($Force.IsPresent) {
    Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $trigger -Description $description -Force | Out-Null
} else {
    Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $trigger -Description $description | Out-Null
}

$registered = Get-ScheduledTask -TaskName $TaskName
$summary = [ordered]@{
    status = "ok"
    taskName = $TaskName
    state = $registered.State.ToString()
    schedule = [ordered]@{
        dayOfWeek = $DayOfWeek
        at = $At
    }
    baseUrl = $BaseUrl
    actor = $Actor
    authTokenEnvVar = $AuthTokenEnvVar
    challengeCodeConfigured = (-not [string]::IsNullOrWhiteSpace($ChallengeCode))
}

$summary | ConvertTo-Json -Depth 5
